2025-01-13 18:25:08,411 INFO    MainThread:3220044 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-01-13 18:25:08,411 INFO    MainThread:3220044 [wandb_setup.py:_flush():68] Configure stats pid to 3220044
2025-01-13 18:25:08,411 INFO    MainThread:3220044 [wandb_setup.py:_flush():68] Loading settings from /home/parsa/.config/wandb/settings
2025-01-13 18:25:08,411 INFO    MainThread:3220044 [wandb_setup.py:_flush():68] Loading settings from /home/parsa/projects/smollm/finetuning/wandb/settings
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_init.py:_log_setup():523] Logging user logs to /home/parsa/projects/smollm/finetuning/wandb/run-20250113_182508-hj7eceii/logs/debug.log
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_init.py:_log_setup():524] Logging internal logs to /home/parsa/projects/smollm/finetuning/wandb/run-20250113_182508-hj7eceii/logs/debug-internal.log
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_init.py:init():641] calling init triggers
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {}
2025-01-13 18:25:08,412 INFO    MainThread:3220044 [wandb_init.py:init():674] starting backend
2025-01-13 18:25:08,619 INFO    MainThread:3220044 [wandb_init.py:init():678] sending inform_init request
2025-01-13 18:25:08,624 INFO    MainThread:3220044 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-13 18:25:08,624 INFO    MainThread:3220044 [wandb_init.py:init():693] backend started and connected
2025-01-13 18:25:08,627 INFO    MainThread:3220044 [wandb_init.py:init():786] updated telemetry
2025-01-13 18:25:08,631 WARNING MsgRouterThr:3220044 [router.py:message_loop():75] message_loop has been closed
2025-01-13 18:25:08,632 INFO    MainThread:3220044 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-13 18:25:13,634 ERROR   MainThread:3220044 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/home/parsa/miniconda3/envs/smollm/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
  File "/home/parsa/miniconda3/envs/smollm/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 821, in init
    result = run_init_handle.wait(
  File "/home/parsa/miniconda3/envs/smollm/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
